export enum MedicalRole {
  PATIENT = 'PATIENT',
  NURSE = 'NURSE',
  DOCTOR = 'DOCTOR',
  SPECIALIST = 'SPECIALIST',
  SURGEON = 'SURGEON',
  HEAD_NURSE = 'HEAD_NURSE',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  ADMIN = 'ADMIN',
  PHARMACIST = 'PHARMACIST',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  RADIOLOGIST = 'RADIOLOGIST',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}
